### ISSUE TITLE
Test partie 1

### ISSUE THREAD

**Issue by NathanLiccardo** [RobinPetit/Projet-INFO-H-303#7]
Hello ! 
Je vient de poster la première partie du programme (page de connection + inscription et menu profil) Chez moi ça ne compile pas ... Est-ce que tu peux test pour voir ce qu'il en est ? Je continuerai de relier le tout demain :) (Tout ce qui est à test est normalement en commentaire)

## TODO

- [x] créer un compte et le lier à la db ;
- [x] se connecter avec un compte dans la db ;
- [x] consulter les informations du compte (les modifier ?) ;
- [x] rechercher un établissement dans la db ;
- [x] commenter un établissement ;
- [x] créer établissements/tags... (*pour les admins*) ;
- [x] créer interface accès pour les requêtes spécifiques ;
- [x] créer interface admin pour pouvoir modifier ses informations ;
- [x] créer interface admin pour pouvoir ajouter un établissement ;
- [x] ajouter la possibilité de tagger un établissement ;
- [x] création des jours de fermeture d'un restaurant ;
- [x] Ajouter la recherche d'un restaurant par différents moyen : type, commune et label.
- [x] Possibilité de chercher un user dans la DB 
- [x] Ajout de la liste des tags aux établissement (fiche descriptive)
- [x] Ajout de l'adresse aux établissements
- [x] Modifier un établissement existant
